### ISSUE TITLE
Debug the issue with put command

### ISSUE THREAD

**Issue by igor-kupczynski** [puszczyk/geeknyte#3]
Do not forget about the automated tests

**Comment by igor-kupczynski** [comment]
Stacktrace is this

```
$ geeknyte put pic.jpg /Shared/Temp/4.jpg

# This is now defunct due to the following. I need to debug it
/usr/lib/node_modules/geeknyte/node_modules/egnyte-js-sdk/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Only files with non zero sizes can be uploaded
    at Request._callback (/usr/lib/node_modules/geeknyte/node_modules/egnyte-js-sdk/src/lib/api_elements/reqengine.js:97:21)
    at Request.self.callback (/usr/lib/node_modules/geeknyte/node_modules/egnyte-js-sdk/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/geeknyte/node_modules/egnyte-js-sdk/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/geeknyte/node_modules/egnyte-js-sdk/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```
